# Generated by Django 5.0.4 on 2024-05-09 19:43

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birthdate',
            field=models.DateField(default=None, validators=[accounts.models.validate_age]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='dni',
            field=models.IntegerField(default=None, error_messages={'unique': 'El DNI ingresado ya se encuentra registrado en el sistema'}, unique=True, validators=[django.core.validators.MinValueValidator(10000000, message='¡Número de DNI invalido!'), django.core.validators.MaxValueValidator(99999999, message='¡Número de DNI invalido!')]),
        ),
    ]
